update-sdk-for-governance-policy-spec-sync
open-cluster-management/governance-policy-spec-sync pull request #66
Opened 2021-11-05 14:24 UTC by ChunxiAlexLuo

Signed-off-by: Chunxi Luo chuluo@redhat.com

2021-11-09 17:31 UTC, ChunxiAlexLuo commented on Makefile
> +	kubectl create ns $(KIND_NAMESPACE) --kubeconfig=$(PWD)/kubeconfig_hub
It seems we also need to create `open-cluster-management-agent-addon` ns on the hub cluster for leader election, correct me if I'm wrong

2021-11-09 17:45 UTC, ChunxiAlexLuo commented
@mprahl @JustinKuli  here the first pr is what I did before our yesterday discussion, I don't squash the second pr `fix e2e testing` for easier reviewing

2021-11-09 20:11 UTC, mprahl requested changes

2021-11-09 20:11 UTC, mprahl commented on main.go
>  	"sigs.k8s.io/controller-runtime/pkg/manager/signals"
Could you please add the following comment after this import?
```go
//+kubebuilder:scaffold:imports
```

2021-11-09 20:11 UTC, mprahl commented on test/e2e/case1_spec_sync_test.go
> +		_, err := utils.KubectlWithOutput("apply", "-f", case1PolicyYaml, "-n", testNamespace,
Could you please explain why this change was made in the commit message? Ideally this change would have been in a separate commit but an explanation would suffice. I'm pretty sure I know why you did it but someone without context would not and so looking at the commit message would help them.

2021-11-09 20:11 UTC, mprahl commented on Makefile
> +	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
`hack/boilerplate.go.txt` seems to be missing. Could you please add it?

2021-11-09 20:11 UTC, mprahl commented on test/resources/case2_uninstall_ns/case2-uninstall-ns.yaml
> +        image: quay.io/open-cluster-management/governance-policy-spec-sync:latest
In the future, it'd be nice to not include things that aren't related to your PR and that don't affect the behavior of the code at all.

2021-11-09 20:11 UTC, mprahl commented on main.go
>  	}
Could you please add the health and readiness checks? For example like this?
https://github.com/open-cluster-management/governance-policy-status-sync/blob/81abad3c816d085c8755b4e6122a6336dfa0a743/main.go#L175-L183

Then you also need to modify the `Deployment` in the `deploy` directory to use them.

2021-11-09 20:11 UTC, mprahl commented on main.go
>  	options := manager.Options{
Could you also please add the ability to fallback to the legacy leader election as shown in this PR?
https://github.com/open-cluster-management/cert-policy-controller/pull/105

This is required for this controller to run on OCP 3.11.

2021-11-10 15:41 UTC, ChunxiAlexLuo commented
health and readiness checks will be added another pr

https://github.com/open-cluster-management/governance-policy-spec-sync/pull/65

2021-11-10 17:17 UTC, mprahl requested changes
Could you also please modify your commit message subject line to something like `Update the operator-sdk` instead of `update-sdk-for-governance-policy-spec-sync`?

2021-11-10 17:17 UTC, mprahl commented on main.go
>  	}
After this line, could you please include the `//+kubebuilder:scaffold:builder` comment?

2021-11-10 17:17 UTC, mprahl commented on controllers/sync/policy_spec_sync.go
> +func (r *PolicyReconciler) Reconcile(ctx context.Context, request reconcile.Request) (reconcile.Result, error) {
I don't see any kubebuilder RBAC markers in this file (i.e. `//+kubebuilder:rbac`). Could you please add them to match what was originally in `deploy/operator.yaml`? It seems the `deploy/rbac/role.yaml` doesn't match what was there previously.

2021-11-10 17:17 UTC, mprahl commented on main.go
> +		// Otherwise it will improperly use hub cluster config as default on ceating a new manager step.
```suggestion
		// Otherwise it will improperly use the hub cluster config for leader election.
```

2021-11-10 21:10 UTC, ChunxiAlexLuo commented
@mprahl 
Don't get what should be matched with `deploy/operator.yaml `in `ClusterRole`, current `role.yaml `looks fine to me, you mean should use `asterisk` for referring all resources under `policy.open-cluster-management.io`? Updated the rest as the suggestions

2021-11-10 21:26 UTC, mprahl commented
> @mprahl Don't get what should be matched with `deploy/operator.yaml `in `ClusterRole`, current `role.yaml `looks fine to me, you mean should use `asterisk` for referring all resources under `policy.open-cluster-management.io`? Updated the rest as the suggestions

I must have misread it. With your latest change with the RBAC kubebuilder markers and the CI verifying, this should be fine!

2021-11-10 21:26 UTC, mprahl approved these changes
Nice job! This looks good to me.

/hold in case you want someone else to review it. If not, feel free to unhold it.

2021-11-10 21:46 UTC, ChunxiAlexLuo commented
/unhold

2021-11-10 21:47 UTC, merged